version: "3.8"
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  backend-old:
    build:
      context: ./delivery-breakfast-old-backend/
      dockerfile: Dockerfile
    container_name: delivery-backend-old
    ports:
      - "3001:3001"
    depends_on:
      - db

  backend-new: 
    build:
      context: ./delivery-breakfast-new-backend/
      dockerfile: Dockerfile
    container_name: delivery-backend-new
    ports:
      - "3002:3002"
    depends_on:
      - db
    
  frontend-old:
    build:
      context: ./delivery-breakfast-old-frontend/
      dockerfile: Dockerfile
    container_name: delivery-frontend-old
    ports:
      - "4001:4001"
    depends_on:
      - backend-old

  frontend-new:
    build:
      context: ./delivery-breakfast-new-frontend/
      dockerfile: Dockerfile
    container_name: delivery-frontend-new
    ports:
      - "4002:4002"
    depends_on:
      - backend-new
